id: mii-ig-studie-2004-de
canonical: https://www.medizininformatik-initiative.de/fhir/ext/modul-studie
name: MII_IG_Studie_2024_DE
# title: Example Title
# description: Example Implementation Guide for getting started with SUSHI
status: active # draft | active | retired | unknown
version: 2024.0.0
fhirVersion: 4.0.1 # https://www.hl7.org/fhir/valueset-FHIR-version.html
copyrightYear: 2019+
releaseLabel: ci-build # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
# license: CC0-1.0 # https://www.hl7.org/fhir/valueset-spdx-license.html
# jurisdiction: urn:iso:std:iso:3166#US "United States of America" # https://www.hl7.org/fhir/valueset-jurisdiction.html
publisher:
  name: Medizininformatikinitiative
  url: https://www.medizininformatik-initiative.de/
FSHOnly: false # true
dependencies:
  de.basisprofil.r4: 1.4.0
  de.medizininformatikinitiative.kerndatensatz.meta: 1.0.3
  hl7.fhir.extensions.r5: 4.0.1
